/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol AFSpeechDelegate <NSObject>
@optional
-(void)assistantConnectionSpeechRecordingWillBegin:(id)assistantConnectionSpeechRecording;
-(void)assistantConnectionSpeechRecordingDidBegin:(id)assistantConnectionSpeechRecording;
-(void)assistantConnectionSpeechRecordingDidEnd:(id)assistantConnectionSpeechRecording;
-(void)assistantConnectionSpeechRecordingDidCancel:(id)assistantConnectionSpeechRecording;
-(void)assistantConnection:(id)connection speechRecordingDidFail:(id)speechRecording;
-(void)assistantConnection:(id)connection speechRecognitionDidFail:(id)speechRecognition;
-(void)assistantConnection:(id)connection didRecognizePhrases:(id)phrases correctionIdentifier:(id)identifier;
-(void)assistantConnection:(id)connection didRecognizeSpeechPhrases:(id)phrases correctionIdentifier:(id)identifier;
@end

