/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import "SBNewsstandItemIconViewBase.h"


@interface SBAppSwitcherNewsstandItemIconView : SBNewsstandItemIconViewBase {
}
+(BOOL)allowsRecycling;
+(id)createBadgeLabelImageAndGetTextCenterPoint:(CGPoint*)point;
+(float)_badgeLabelFontSize;
+(CGPoint)badgeLabelCenterPoint;
-(void)positionCloseBoxOfType:(int)type;
-(void)positionIconImageView;
-(float)_badgeHorizontalPadding;
-(float)_badgeVerticalPadding;
-(id)_superviewForBadge;
-(id)_overriddenBadgeTextForText:(id)text;
@end

