/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, NSString, NSArray;

@interface SBAssistantGuideSectionModel : XXUnknownSuperclass {
	NSString* _title;
	NSMutableArray* _phrases;
}
@property(retain, nonatomic) NSString* title;
@property(retain, nonatomic) NSArray* phrases;
-(id)init;
-(void)dealloc;
@end

