/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBAssistantController;

@interface SBAssistantFullyRevealedState : XXUnknownSuperclass {
	SBAssistantController* _controller;
	id _block;
}
@property(retain, nonatomic) SBAssistantController* controller;
@property(retain, nonatomic) id block;
+(id)stateWithController:(id)controller block:(id)block;
-(void)dealloc;
@end

