/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import "SBBulletinImageView.h"

@class UIView;

@interface SBBulletinLinenSegmentView : SBBulletinImageView {
	UIView* _linenView;
	CGSize _linenSize;
	SBBulletinImageView* _gradientView;
}
-(id)initWithFrame:(CGRect)frame linenView:(id)view;
-(void)dealloc;
-(void)adjustContents;
-(void)setGradientAlpha:(float)alpha;
-(void)setFrame:(CGRect)frame;
-(void)didMoveToWindow;
@end

