/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImageView;

@interface SBBulletinCellSelectionView : XXUnknownSuperclass {
	UIImageView* _gradientView;
	float _cellSeparatorHeight;
}
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)setCellSeparatorHeight:(float)height;
-(void)layoutSubviews;
@end

