/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBDeviceLockViewWithKeyboard;

@interface SBDeviceLockKeyboard : XXUnknownSuperclass {
	SBDeviceLockViewWithKeyboard* _deviceLockView;
}
-(id)initWithFrame:(CGRect)frame deviceLockView:(id)view;
-(BOOL)canDismiss;
-(void)minimize;
-(void)maximize;
-(void)setMinimized:(BOOL)minimized;
-(BOOL)isMinimized;
@end

