/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDateFormatter;

@interface SBDefaultDateLabelDateFormatCache : XXUnknownSuperclass {
	NSDateFormatter* _dayOfWeekFormatter;
	NSDateFormatter* _dayMonthYearFormatter;
	NSDateFormatter* _dayMonthFormatter;
	NSDateFormatter* _timeFormatter;
}
-(id)init;
-(void)dealloc;
-(void)resetFormattersIfNecessary;
-(void)resetFormatters:(id)formatters;
-(id)formatDateAsDayOfWeek:(id)week;
-(id)formatDateAsDayMonthYearStyle:(id)style;
-(id)formatDateAsDayMonthStyle:(id)style;
-(id)formatDateAsTimeStyle:(id)style;
@end

