/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import "SBDeviceLockKeypad.h"

@class UIImage, UIButton;

@interface SBDeviceLockKeypadPhone : SBDeviceLockKeypad {
	UIButton* _emergencyCallButton;
	UIButton* _poundButton;
	UIImage* _deleteIcon;
}
+(id)keypadImage;
+(id)pressedImage;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(float)_yFudge;
-(BOOL)showsEmergencyCallButton;
-(void)setShowsEmergencyCallButton:(BOOL)button;
-(void)setDeleteEnabled:(BOOL)enabled;
-(BOOL)deleteKeyChar;
-(BOOL)cancelKeyChar;
-(BOOL)emergencyKeyChar;
-(void)_updateCancelAndDeleteButtons;
@end

