/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SBDiskSpaceAlertItem : XXUnknownSuperclass {
	int _usageButtonIndex;
}
-(void)performUnlockAction;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)_showUsagePrefs;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(BOOL)shouldShowInEmergencyCall;
@end

