/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import "SBLeafIcon.h"

@class NSMutableArray, NSString, NSOperation, SSDownloadStatus, SSDownload;

@interface SBDownloadingIcon : SBLeafIcon {
	NSString* _leafIdentifier;
	NSString* _applicationBundleID;
	SSDownload* _download;
	float _progress;
	BOOL _installing;
	BOOL _wasUninstalledByUser;
	BOOL _isNewsstandDownload;
	SSDownloadStatus* _lastStatus;
	SSDownload* _downloadForImageDataBeingLoaded;
	NSOperation* _iconImageGenerationOperation;
	NSMutableArray* _imageCacheFilePaths;
	BOOL _imageCacheBeingRead;
}
+(dispatch_queue_s*)backgroundQueue;
+(id)__imageCacheDirectoryPath;
+(void)setupDownloadingIconImageCache;
+(id)leafIdentifierForDownloadUniqueID:(id)downloadUniqueID;
+(id)leafIdentifierForDownload:(id)download;
+(id)__darkenedIconImageForImage:(id)image;
+(id)__iconImageFromData:(id)data format:(int)format scale:(float)scale options:(int)options darken:(BOOL)darken;
-(id)initWithLeafIdentifier:(id)leafIdentifier;
-(id)initWithDownload:(id)download;
-(void)dealloc;
-(BOOL)matchesRepresentation:(id)representation;
-(id)representation;
-(id)description;
-(void)setLeafIdentifier:(id)identifier;
-(id)identifierForCorrespondingApplicationIcon;
-(id)undarkenedHomeScreenIconImage;
-(int)_iconImageOptions;
-(id)getGenericIconImage:(int)image;
-(int)iconFormatForLocation:(int)location;
-(BOOL)shouldCacheImageForFormat:(int)format;
-(void)loadAndDarkenHomeScreenIconImageInBackground;
-(void)_reloadThumbnailImage;
-(void)_removeImageCacheFileAtPath:(id)path;
-(id)generateIconImage:(int)image;
-(BOOL)canEllipsizeLabel;
-(id)displayName;
-(id)realDisplayName;
-(id)leafIdentifier;
-(void)launch;
-(BOOL)allowsUninstall;
-(void)completeUninstall;
-(void)reloadForStatusChange;
-(float)progress;
-(BOOL)isDone;
-(id)applicationBundleID;
-(void)setApplicationBundleID:(id)anId;
-(void)setDownload:(id)download;
-(id)download;
-(BOOL)isNewsstandDownload;
-(void)setNewsstandDownload:(BOOL)download;
-(void)retry;
-(void)remove;
-(BOOL)uninstalledByUser;
-(void)setUninstalledByUser:(BOOL)user;
-(id)uninstallAlertTitle;
-(id)uninstallAlertBody;
-(id)uninstallAlertConfirmTitle;
-(id)uninstallAlertCancelTitle;
-(void)_showAlertForError:(id)error;
-(BOOL)iconAppearsInNewsstand;
@end

