/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface SBFolderScrollOffset : XXUnknownSuperclass {
	CGPoint _scrollOffset;
	unsigned _identifier;
	int _orientation;
}
@property(assign) CGPoint scrollOffset;
@property(assign) int orientation;
@property(assign) unsigned identifier;
@end

