/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSSet;

@interface SBFolderRotationAnimationContext : XXUnknownSuperclass {
	NSSet* _icons;
	XXStruct_9ihRqB _notchInfo;
	double _duration;
}
@property(retain, nonatomic) NSSet* icons;
@property(assign, nonatomic) XXStruct_9ihRqB notchInfo;
@property(assign, nonatomic) double duration;
-(void)dealloc;
@end

