/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, NSDictionary, NSMutableSet;

@interface SBHostRequesterInfo : XXUnknownSuperclass {
	UIView* _wrapperView;
	NSMutableSet* _hiddenContexts;
	NSDictionary* _realContextHostViewChangedProperties;
	NSDictionary* _realContextHostViewOriginalProperties;
}
@property(readonly, assign, nonatomic) UIView* wrapperView;
@property(readonly, assign, nonatomic) NSMutableSet* hiddenContexts;
@property(retain, nonatomic) NSDictionary* realContextHostViewChangedProperties;
@property(retain, nonatomic) NSDictionary* realContextHostViewOriginalProperties;
-(id)init;
-(void)dealloc;
@end

