/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface SBIconBadgeImage : XXUnknownSuperclass {
	NSString* _text;
	int _checkoutCount;
}
@property(readonly, copy) NSString* text;
@property(assign) int checkoutCount;
-(id)initWithCGImage:(CGImageRef)cgimage scale:(float)scale orientation:(int)orientation text:(id)text;
-(void)dealloc;
@end

