/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import "NSCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface SBIconLabelProperties : XXUnknownSuperclass <NSCopying> {
	NSString* _text;
	NSString* _labelClassString;
	BOOL _ellipsize;
	BOOL _inDock;
	BOOL _onWallpaper;
	CGSize _size;
	BOOL _appearsInDock;
	BOOL _appearsOnWallpaper;
}
@property(retain, nonatomic) NSString* text;
@property(assign, nonatomic) BOOL ellipsize;
@property(assign, nonatomic) BOOL appearsInDock;
@property(assign, nonatomic) BOOL appearsOnWallpaper;
@property(assign, nonatomic) CGSize size;
@property(assign, nonatomic) Class labelClass;
-(id)labelClassString;
-(void)dealloc;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(id)copyWithZone:(NSZone*)zone;
-(id)description;
@end

