/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBNewsstandTilingImageView, SBNewsstandShelfHeaderView;

@interface SBNewsstandShelfFrameView : XXUnknownSuperclass {
	CGSize _borderSize;
	SBNewsstandShelfHeaderView* _headerView;
	SBNewsstandTilingImageView* _leftBorder;
	SBNewsstandTilingImageView* _rightBorder;
	int _orientation;
}
+(void)setupCache;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)showHeaderView;
-(void)setFrame:(CGRect)frame;
-(void)configureForOrientation:(int)orientation;
-(void)layoutSubviews;
@end

