/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import "SBNewsstandTilingImageView.h"

@class UIImageView;

@interface SBNewsstandShelfHeaderView : SBNewsstandTilingImageView {
	float _borderWidth;
	UIImageView* _appleLogo;
	UIImageView* _middleShadow;
	UIImageView* _shelvesTopShading;
	int _orientation;
}
+(id)_pathForCachedBackgroundTile;
+(id)_backgroundTileImage;
+(void)setupCache;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)configureForOrientation:(int)orientation;
-(void)layoutSubviews;
@end

