/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBLeafIcon.h"


@interface SBPrintStatusIcon : SBLeafIcon {
}
-(id)generateIconImage:(int)image;
-(id)displayName;
-(id)leafIdentifier;
-(BOOL)shouldEllipsizeLabel;
-(id)applicationBundleID;
-(BOOL)delaysUnhighlightWhenTapped;
@end

