/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Springboard-Structs.h"


@interface SBShowcaseContext : XXUnknownSuperclass {
	int _appOrientation;
	int _showcaseOrientation;
	CGAffineTransform _portraitRelativeViewTransform;
	CGAffineTransform _currentReleativeViewTransform;
	BOOL _onSpringBoard;
	BOOL _onApp;
	float _offset;
}
@property(assign, nonatomic) int appOrientation;
@property(assign, nonatomic) int showcaseOrientation;
@property(assign, nonatomic) CGAffineTransform portraitRelativeViewTransform;
@property(assign, nonatomic) CGAffineTransform currentReleativeViewTransform;
@property(assign, nonatomic) BOOL onSpringBoard;
@property(assign, nonatomic) BOOL onApp;
@property(assign, nonatomic) float offset;
@end

