/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, CAMutableMeshTransform;

@interface SBStretchTransformer : XXUnknownSuperclass {
	UIView* m_view;
	int m_anchorEdge;
	int m_orientation;
	CAMutableMeshTransform* m_mesh;
	float m_stretchFactor;
	id m_animationCompletionHandler;
}
@property(retain, nonatomic) UIView* view;
@property(assign, nonatomic) int anchorEdge;
@property(assign, nonatomic) int orientation;
@property(assign, nonatomic) float stretchFactor;
-(id)initWithView:(id)view anchorEdge:(int)edge orientation:(int)orientation;
-(void)dealloc;
-(id)meshTransform;
-(void)updateMeshTransform:(id)transform stretchFactor:(float)factor;
-(void)animateToZeroStretchFactor;
-(void)animateToZeroStretchFactorWithCompletionHandler:(id)completionHandler;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
@end

