/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface SBSwitcherSlider : XXUnknownSuperclass {
}
-(id)initWithFrame:(CGRect)frame;
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
-(CGRect)trackRectForBounds:(CGRect)bounds;
-(CGRect)thumbRectForBounds:(CGRect)bounds trackRect:(CGRect)rect value:(float)value;
-(UIEdgeInsets)_thumbHitEdgeInsets;
@end

