/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SBSystemLocalNotificationAlertSheet : XXUnknownSuperclass {
	BOOL _lockToPortrait;
}
-(void)setLockToPortrait:(BOOL)portrait;
-(BOOL)requiresPortraitOrientation;
@end

