/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface SBUIRootView : XXUnknownSuperclass {
	BOOL _animatingAlpha;
}
-(id)initWithFrame:(CGRect)frame;
-(void)_actuallySetAlpha:(float)alpha;
-(void)setAlpha:(float)alpha;
-(BOOL)_shouldAnimatePropertyWithKey:(id)key;
@end

