/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage;

@interface SBUserNotificationAlertSheet : XXUnknownSuperclass {
	UIImage* _alertImage;
}
@property(retain, nonatomic) UIImage* alertImage;
-(void)dismissWithClickedButtonIndex:(int)clickedButtonIndex animated:(BOOL)animated;
-(void)layout;
-(void)dealloc;
-(id)_maskedAlertImage;
@end

