/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBWallpaperClipView;

@interface SBWallpaperNotchView : XXUnknownSuperclass {
	XXStruct_9ihRqB _notchInfo;
	SBWallpaperClipView* _clipView;
}
-(id)initWithFrame:(CGRect)frame wallpaperView:(id)view notchInfo:(XXStruct_9ihRqB)info;
-(void)dealloc;
-(void)setNotchInfo:(XXStruct_9ihRqB)info;
-(void)drawRect:(CGRect)rect;
@end

