//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBSearchResultsModalViewControllerAction.h"

#import "_MKPlaceViewControllerFeedbackDelegate.h"

@class MKMapItem, NSString;

@interface SBSearchResultsMapsAction : SBSearchResultsModalViewControllerAction <_MKPlaceViewControllerFeedbackDelegate>
{
    MKMapItem *_mapItem;
}

@property(retain, nonatomic) MKMapItem *mapItem; // @synthesize mapItem=_mapItem;
- (void)performButtonAction;
- (id)buttonActionTitle;
- (void)placeViewController:(id)arg1 shouldLogFeedbackOfType:(int)arg2;
- (void)loadModalViewControllerWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

