//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBStarkSessionConfiguring.h"

@class AVExternalDevice, NSSet, NSString, UIScreen, UITraitCollection;

@interface SBStarkSessionConfiguration : NSObject <SBStarkSessionConfiguring>
{
    AVExternalDevice *_device;
    unsigned long long _interactionAffordances;
    long long _layoutJustification;
    UIScreen *_screen;
    UITraitCollection *_traitCollection;
    _Bool _geoSupported;
    NSSet *_protocols;
}

@property(copy, nonatomic) NSSet *sessionProtocols;
@property(nonatomic, getter=isGeoSupported) _Bool geoSupported;
@property(readonly, copy, nonatomic) UITraitCollection *traitCollection;
@property(readonly, retain, nonatomic) UIScreen *screen;
@property(readonly, nonatomic) long long layoutJustification;
@property(readonly, nonatomic) unsigned long long interactionAffordances;
@property(readonly, retain, nonatomic) AVExternalDevice *device;
- (void)dealloc;
- (id)initWithDevice:(id)arg1 screen:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

