/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import "NSObject.h"


@protocol AFUISnippetDelegate <NSObject>
-(id)snippetControllerViewController:(id)controller;
-(void)snippetController:(id)controller changeSizeTo:(CGSize)to;
-(void)snippetControllerRemoveView:(id)view;
-(void)snippetController:(id)controller sendGenericAceCommand:(id)command;
-(id)snippetController:(id)controller domainObjectForIdentifier:(id)identifier;
-(id)snippetControllerEffectiveBundleForCoreLocation:(id)coreLocation;
-(BOOL)snippetControllerIsDevicePasscodeLocked:(id)locked;
@end

