/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol AFUIUtteranceViewDelegate <NSObject>
@optional
-(BOOL)utteranceViewTextShouldPreventCorrection:(id)utteranceViewText;
-(void)utteranceViewTextWillBeginCorrecting:(id)utteranceViewText;
-(void)utteranceViewTextDidChange:(id)utteranceViewText;
-(void)utteranceViewTextDidFinishCorrecting:(id)utteranceViewText;
-(void)utteranceViewInfoButtonHit:(id)hit;
@end

