/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, CALayer, CATransformLayer, SBApplication;

@interface SBAppToAppTransitionView : XXUnknownSuperclass {
	id _delegate;
	SBApplication* _toApplication;
	CATransformLayer* _transformLayer;
	CALayer* _startLayer;
	CALayer* _stopLayer;
	UIView* _fromView;
	UIView* _toView;
	BOOL _animating;
	BOOL _workspaceIsReadyForAnimationCleanup;
	int _orientation;
}
@property(assign, nonatomic) id delegate;
@property(retain, nonatomic) SBApplication* toApp;
@property(assign, nonatomic) int orientation;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)setFromView:(id)view;
-(void)setToView:(id)view;
-(void)beginTransition;
-(void)endTransition;
-(void)noteWorkspaceIsReadyForAnimationCleanupWithActivatingApp:(id)activatingApp;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
-(id)_rotationValueFunction;
-(float)_rotationRadians;
-(void)_transitionBegun:(double)begun;
@end

