/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImageView, UILabel;

@interface SBAssistantUnavailableView : XXUnknownSuperclass {
	UILabel* _titleLabel;
	UILabel* _subtitleLabel;
	UIImageView* _embossedMic;
}
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)layoutSubviews;
@end

