/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel;

@interface SBAssistantBasicView : XXUnknownSuperclass {
	UILabel* _title;
	UILabel* _subtitle;
}
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)setTitleText:(id)text;
-(void)setSubtitleText:(id)text;
-(void)layoutSubviews;
@end

