/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "AFUIUtteranceViewDelegate.h"

@class AFUIUserUtteranceView, NSString, SBAssistantUserUtterance;

@interface SBAssistantUserUtteranceController : XXUnknownSuperclass <AFUIUtteranceViewDelegate> {
	SBAssistantUserUtterance* _utterance;
	NSString* _preCorrectionText;
	CGSize _currentTextSize;
	BOOL _textChanged;
	BOOL _correctable;
	AFUIUserUtteranceView* _view;
}
+(id)controllerWithUtterance:(id)utterance isCorrectable:(BOOL)correctable delegate:(id)delegate;
-(id)initWithUtterance:(id)utterance isCorrectable:(BOOL)correctable delegate:(id)delegate;
-(void)dealloc;
-(void)_updateViewWithCurrentUtterance;
-(id)view;
-(id)text;
-(id)correctionIdentifier;
-(BOOL)isCorrectable;
-(void)setIsCorrectable:(BOOL)correctable;
-(void)updateWithUtterance:(id)utterance;
-(void)_checkUpdatedSizingForUtteranceView:(id)utteranceView;
-(BOOL)_isServerResponse;
-(id)description;
-(BOOL)utteranceViewTextShouldPreventCorrection:(id)utteranceViewText;
-(void)utteranceViewTextWillBeginCorrecting:(id)utteranceViewText;
-(void)utteranceViewTextDidChange:(id)utteranceViewText;
-(void)utteranceViewTextDidFinishCorrecting:(id)utteranceViewText;
@end

