/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SBAssistantMicImages : XXUnknownSuperclass {
}
+(void)initialize;
+(unsigned)listeningImageCount;
+(unsigned)thinkingImageCount;
+(unsigned)fullImageCount;
+(id)listeningImageAtIndex:(unsigned)index;
+(id)thinkingImageAtIndex:(unsigned)index;
+(id)fullImageAtIndex:(unsigned)index;
+(id)thinkingOnImage;
@end

