/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAssistantSpaceViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBAssistantSpaceView;

@interface SBAssistantSpaceController : XXUnknownSuperclass <SBAssistantSpaceViewDelegate> {
	float _space;
	SBAssistantSpaceView* _view;
}
@property(assign, nonatomic) float space;
-(id)initWithAceObject:(id)aceObject delegate:(id)delegate;
-(void)dealloc;
-(id)view;
-(float)assistantSpaceViewIdealHeight:(id)height;
-(BOOL)_wantsUnmodifiedHeight;
-(BOOL)_affectsMagicPocket;
@end

