/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView;

@interface SBAssistantAwayBottomView : XXUnknownSuperclass {
	UIView* _lockBarView;
	UIView* _backgroundView;
	BOOL _open;
}
-(id)initWithFrame:(CGRect)frame;
-(id)initWithAwayView:(id)awayView;
-(void)dealloc;
-(void)layoutSubviews;
-(void)setOpen:(BOOL)open;
@end

