/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import "SBAlertDisplay.h"

@class UIView;

@interface SBAssistantAlertDisplay : SBAlertDisplay {
	UIView* _assistantView;
}
@property(retain, nonatomic) UIView* assistantView;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)layoutSubviews;
-(void)alertDisplayWillBecomeVisible;
-(void)alertDisplayBecameVisible;
@end

