/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBAwayBulletinListView;

@interface SBAwayBulletinGrabberView : XXUnknownSuperclass {
	BOOL _tracking;
	float _centerDelta;
	SBAwayBulletinListView* _listView;
}
-(id)initWithFrame:(CGRect)frame andView:(id)view;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
@end

