/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class CALayer;

@interface SBBuddyLogoZoomView : XXUnknownSuperclass {
	CALayer* _contentLayer;
	id _animationCompleteBlock;
}
-(id)initWithFrame:(CGRect)frame;
-(void)startAnimationWithCompletionBlock:(id)completionBlock;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
@end

