/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBBulletinDateLabel <NSObject>
@property(assign, nonatomic, getter=isAllDay) BOOL allDay;
-(void)setStartDate:(id)date withTimeZone:(id)timeZone;
-(void)setEndDate:(id)date withTimeZone:(id)timeZone;
@end

