/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBBulletinAlertHandlerRegistry.h"

@class NSMutableDictionary;

@protocol SBBulletinAlertHandlerRegistry
-(void)addAlertHandler:(id)handler forSection:(id)section;
@end

@interface SBBulletinAlertHandlerRegistry : XXUnknownSuperclass <SBBulletinAlertHandlerRegistry> {
	NSMutableDictionary* _handlersBySectionID;
}
-(id)init;
-(void)dealloc;
-(id)alertHandlersForSection:(id)section;
-(void)addAlertHandler:(id)handler forSection:(id)section;
@end

