/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import "SBBulletinLinenBackedCell.h"

@class NSTimer, UIImageView, SBBulletinCellContentView, NSDate;

@interface SBBulletinListCell : SBBulletinLinenBackedCell {
	UIImageView* _bulletinAccessoryView;
	UIImageView* _bottomCellSeparator;
	SBBulletinCellContentView* _cellContentView;
	NSDate* _futureDate;
	NSTimer* _futureDateTimer;
}
@property(retain) NSDate* futureDate;
+(float)heightForRowWithSubtitle:(id)subtitle message:(id)smessage maxLines:(unsigned)lines width:(float)width italicize:(BOOL)italicize;
+(float)heightForRowWithSubtitle:(id)subtitle imageHeight:(float)height italicize:(BOOL)italicize;
-(id)initWithLinenView:(id)linenView reuseIdentifier:(id)identifier;
-(void)dealloc;
-(void)_clearFutureDateTimer;
-(void)willMoveToSuperview:(id)superview;
-(void)prepareForReuse;
-(void)setHighlighted:(BOOL)highlighted;
-(void)setMaxMessageLines:(unsigned)lines;
-(void)setTitle:(id)title;
-(void)setSubtitle:(id)subtitle;
-(void)setMessage:(id)message;
-(void)setStartDate:(id)date endDate:(id)date2 timeZone:(id)zone allDay:(BOOL)day formatStyle:(int)style;
-(void)setAttachmentImage:(id)image;
-(void)setAttachmentImageSize:(CGSize)size;
-(void)setAttachmentText:(id)text;
-(void)setBulletinAccessoryStyle:(int)style;
-(void)setCellSeparatorStyle:(int)style;
-(void)setContentItalicizedUntil:(id)until;
-(void)_futureDateTimerFired:(id)fired;
-(void)layoutSubviews;
@end

