/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UIGestureRecognizerDelegate.h"


@interface SBBulletinListTouchEater : XXUnknownSuperclass <UIGestureRecognizerDelegate> {
}
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(BOOL)canBePreventedByGestureRecognizer:(id)recognizer;
@end

