/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SBBulletinHeaderViewDelegate.h"

@class UIView, UIImageView, SBBulletinLinenSegmentView, NSMutableSet;

@interface SBBulletinTableView : XXUnknownSuperclass <SBBulletinHeaderViewDelegate> {
	NSMutableSet* _visibleSectionHeaders;
	UIView* _fadeContainer;
	SBBulletinLinenSegmentView* _fadeSegment;
	UIImageView* _fadeOverlayMask;
}
-(id)initWithFrame:(CGRect)frame linenView:(id)view;
-(void)dealloc;
-(id)visibleSectionHeaders;
-(void)setRasterizesFadeOverlay:(BOOL)overlay;
-(void)setLinenGradientAlpha:(float)alpha;
-(void)layoutSubviews;
-(void)headerViewWillAppear:(id)headerView;
-(void)headerViewWillDisappear:(id)headerView;
@end

