/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITableViewDataSource.h"
#import "Springboard-Structs.h"
#import "UITableViewDelegate.h"
#import "NSObject.h"
#import "UIGestureRecognizerDelegate.h"


@protocol SBBulletinListViewDelegate <NSObject, UITableViewDelegate, UITableViewDataSource, UIGestureRecognizerDelegate>
-(void)handleTap:(id)tap;
-(void)handlePan:(id)pan;
-(void)handleEatenTouch:(id)touch;
@end

