/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSMutableDictionary;

@interface SBMappedImageCache : XXUnknownSuperclass {
	dispatch_queue_s* _queue;
	NSString* _path;
	NSMutableDictionary* _images;
}
+(id)persistentCache;
+(id)sessionCache;
+(id)imageNamed:(id)named;
-(id)initWithPath:(id)path;
-(void)dealloc;
-(id)imageForKey:(id)key generateImageWithBlockIfNecessary:(id)blockIfNecessary;
-(void)setImage:(id)image forKey:(id)key;
-(id)imageForKey:(id)key;
-(void)removeImageForKey:(id)key;
-(void)removeAllObjects;
@end

