/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import "SBIconLabelProperties.h"

@class NSString;

@interface SBMutableIconLabelProperties : SBIconLabelProperties {
}
@property(retain, nonatomic) NSString* text;
@property(assign, nonatomic) Class labelClass;
@property(assign, nonatomic) BOOL ellipsize;
@property(assign, nonatomic) BOOL appearsInDock;
@property(assign, nonatomic) BOOL appearsOnWallpaper;
@property(assign, nonatomic) CGSize size;
@end

