/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import "SBIconLabel.h"


@interface SBNewsstandIconLabel : SBIconLabel {
}
-(id)_textColor;
-(id)_textShadowColor;
-(CGSize)_textShadowOffset;
-(id)_textFont;
@end

