/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import "SBIconView.h"


@interface SBNewsstandItemIconViewBase : SBIconView {
}
+(BOOL)allowsRecycling;
+(id)createBadgeLabelImageAndGetTextCenterPoint:(CGPoint*)point;
+(float)_badgeLabelFontSize;
+(CGPoint)badgeLabelCenterPoint;
+(BOOL)_hasBadgeLabel;
-(void)iconImageDidUpdate:(id)iconImage;
-(CGRect)_adjustProspectiveBadgeFrame:(CGRect)frame fromView:(id)view toView:(id)view3;
-(void)_updateBadgePosition;
-(id)_superviewForBadge;
-(float)_badgeHorizontalPadding;
-(float)_badgeVerticalPadding;
@end

