/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Springboard-Structs.h"
#import "UITextFieldDelegate.h"

@class NSString;

@interface SBPasscodeAlertItem : XXUnknownSuperclass <UITextFieldDelegate> {
	int _mode;
	int _unlockScreenType;
	NSString* _errorString;
	BOOL _hasEmergencyCall;
}
-(id)initWithPasscodeMode:(int)passcodeMode unlockScreenType:(int)type;
-(void)dealloc;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)returnKeyPressed:(id)pressed;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(BOOL)shouldShowInLockScreen;
-(void)dismiss:(int)dismiss;
-(void)_setErrorString:(id)string;
-(void)didEndCall;
@end

