/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBShowcaseController;

@interface SBShowcaseViewController : XXUnknownSuperclass {
	SBShowcaseController* _showcase;
	int _revealMode;
}
@property(assign, nonatomic) SBShowcaseController* showcase;
@property(assign, nonatomic) int revealMode;
-(id)view;
-(void)viewWillAppear;
-(void)viewDidAppear;
-(void)viewWillDisappear;
-(void)viewDidDisappear;
-(void)viewWillRotateToInterfaceOrientation:(int)view;
-(void)viewDidRotateFromInterfaceOrientation:(int)view;
-(float)bottomBarHeight;
-(BOOL)expectsFaceContact;
-(BOOL)shouldShowLockStatusBarTime;
-(BOOL)shouldShowLockStatusBarIcon;
@end

