/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Springboard-Structs.h"


@interface SBTetherController : XXUnknownSuperclass {
	int _tetherState;
	unsigned _demoCardConnection;
	int _lastOrientationCode;
	BOOL _orientationNotificationsDisabled;
}
@property(assign, nonatomic, getter=isOrientationNotificationDisabled) BOOL orientationNotificationDisabled;
+(id)sharedInstance;
-(id)init;
-(unsigned)_demoCardConnection;
-(void)_postDisplayPortNotificationCode:(int)code;
-(void)_setTetherState:(int)state;
-(BOOL)isTethered;
-(BOOL)usesDisplayPortTethering;
-(void)_handleDemoModeChanged;
-(void)noteInterfaceOrientationChanged;
-(void)setDitheringEnabled:(int)enabled;
-(BOOL)_serviceExists:(CFStringRef)exists;
-(BOOL)_reverseTetheringActive;
-(void)updatePreferencesIfNeeded;
-(void)dealloc;
@end

