/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Springboard-Structs.h"
#import "SBManualKeyboardTextField.h"


@interface WhiteBorderedTextField : SBManualKeyboardTextField {
}
-(void)drawBorder:(CGRect)border;
-(CGRect)textRect;
-(void)drawRect:(CGRect)rect;
@end

