//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSArray, NSDate, NSString;

@interface SBAppSwitcherPeopleContactItem : NSObject <NSCopying>
{
    NSString *_name;
    unsigned long long _nameFormatHash;
    NSArray *_contactActions;
    int _personRecordID;
    NSDate *_recordLastUpdatedDate;
}

@property(copy, nonatomic) NSDate *recordLastUpdatedDate; // @synthesize recordLastUpdatedDate=_recordLastUpdatedDate;
@property(copy, nonatomic) NSArray *contactActions; // @synthesize contactActions=_contactActions;
@property(readonly, nonatomic) int personRecordID; // @synthesize personRecordID=_personRecordID;
@property(nonatomic) unsigned long long nameFormatHash; // @synthesize nameFormatHash=_nameFormatHash;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (_Bool)hasFaceTimeAudioAction;
- (_Bool)hasFaceTimeAction;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (void)dealloc;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithName:(id)arg1 nameFormatHash:(unsigned long long)arg2 abRecordID:(int)arg3 lastUpdated:(id)arg4 contactActions:(id)arg5;

@end

